# Generated by Django 5.0.2 on 2024-02-08 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to='uploads/')),
                ('flow', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.IntegerField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.DecimalField(decimal_places=1, max_digits=9)),
                ('date', models.DateTimeField()),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.file')),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.meter')),
                ('mpan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.mpan')),
            ],
        ),
    ]
